pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: busybox-dev

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - docker run --rm busybox-dev /bin/sh -xec 'true'
      - docker run --rm busybox-dev /bin/sh -xec 'test -f /lib/libc-*.so'
      - docker run --rm busybox-dev /bin/sh -xec 'ldconfig -p'
      - docker run --rm busybox-dev /bin/sh -xec 'nslookup google.com'
      - test "$(docker run --rm busybox-dev /bin/sh -xec 'date +%Z')" = 'UTC'
      - test "$(docker run --rm busybox-dev /bin/sh -xec 'echo This is a test string | md5sum | cut -f1 -d\ ' | tee /dev/stderr)" = 'b584c39f97dfe71ebceea3fdb860ed6c'

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: busybox-dev
    repo: spritsail/busybox
    tags:
      - 'latest'
      - '%label: io.spritsail.version.busybox'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
