---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: busybox-dev

- name: test
  pull: never
  image: busybox-dev
  commands:
  - true
  - test -f /lib/libc-*.so
  - ldconfig -p
  - nslookup google.com
  - test "$(date +%Z)" = 'UTC'
  - test "$(echo This is a test string | md5sum | cut -f1 -d' ' | tee /dev/stderr)" = 'b584c39f97dfe71ebceea3fdb860ed6c'

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: busybox-dev
    repo: spritsail/busybox
    tags:
    - latest
    - "%label io.spritsail.version.busybox"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: d30c74969375fb412dd5161613172be1fa834d76f8934866a76ddd69043b975e

...
