pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build --no-cache --pull -t busybox-dev .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run --rm busybox-dev /bin/sh -xec 'true'
      - docker run --rm busybox-dev /bin/sh -xec 'test -f /lib/libc-*.so'
      - docker run --rm busybox-dev /bin/sh -xec 'ldconfig -p'
      - docker run --rm busybox-dev /bin/sh -xec 'nslookup google.com'
      - test "$(docker run --rm busybox-dev /bin/sh -xec 'date +%Z')" = 'UTC'
      - test "$(docker run --rm busybox-dev /bin/sh -xec 'echo This is a test string | md5sum | cut -f1 -d\ ' | tee /dev/stderr)" = 'b584c39f97dfe71ebceea3fdb860ed6c'

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    when:
      event: [push, tag, deployment]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker tag busybox-dev adamant/busybox:latest
      - docker tag busybox-dev adamant/busybox:1.1
      - docker push adamant/busybox
      - docker rmi busybox-dev adamant/busybox
  
  downstream:
    image: plugins/downstream
    when:
      event: [push, tag, deployment]
    secrets: [ DOWNSTREAM_TOKEN ]
    server: https://drone.adam-ant.co.uk
    fork: true
    repositories:
      - Adam-Ant/docker-busybox@libressl
    when:
      event:  [ push, tag, deployment]
      status: [ success ]
